export const routeInfo = {
  LANDING_SCREEN: 'Dashboard',
  LOG_IN: 'Log In',
  SIGN_UP: 'Sing Up',
  DASHBOARD: 'Dashboard',
  HOME_SCREEN: 'Home',
  CONTACTS: 'Contacts',
  TRANSACTIONS: 'Transactions',
  SEND_MONEY: 'Send Money',
  RECEIVE_MONEY: 'Receive Money',
  QR_SCANNER: 'QR Scanner',
  PAYMENT_STATUS: 'Payment Status',
  TRANSACTIONS_INFO: 'Transactions Info',
  MAKE_QR_CODE_PAYMENT_INFO: 'QR Code Payment',
  ADD_NEW_CONTACT: 'Add New Contact',
};
