export const FETCH_DATA = 'FETCH_DATA';
export const DATA_FETCH_SUCCESSFUL = 'DATA_FETCH_SUCCESSFUL';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';

// related to user Sing-In
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

// related to user Sing-In
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

// related to user Sing-up
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

// related to users
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESSFUL = 'GET_USER_INFO_SUCCESSFUL';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESSFUL = 'GET_ALL_USERS_SUCCESSFUL';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
